name: Resonate Insider
favicon: null
layout_spectrum: 0.74596
typography_spectrum: 0.55339
title: Inside Resonate IT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#666666'
    - '#018fd2'
    - '#cdcfd1'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
