name: Resonate Insider
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19457
title: Inside Resonate IT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfff4'
    - '#000000'
    - '#3a86c2'
    - '#bababa'
    - '#2e2e2e'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
