name: Resonate Insider
favicon: null
layout_spectrum: 0.2811812327709049
typography_spectrum: 0.08138971333391964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.04602046683430672
  lightness: 0.6766091526951641
  saturation: 0.6200947624165565
  rhythmicContrast: 0.03237372497096658
purpose: []
